name: Deploy Lambda on AWS

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Permet un déclenchement manuel

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installer Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Configurer AWS credentials avec clés d'accès
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  # Utilisation du secret
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # Utilisation du secret
          aws-region: eu-west-3

      # - name: LS
      #   run: ls

      - name: Initialiser Terraform
        run: terraform init

      # - name: Vérifier le plan Terraform
      #   run: terraform plan

      # - name: Appliquer Terraform (déploiement)
      #   run: terraform apply -auto-approve

      # - name: Récupérer l'URL de l'API
      #   run: echo "API URL: $(terraform output api_gateway_url)"
